# -*- coding: utf-8 -*-
"""EJERCICIOSFUNCIONES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QBS-GciLGv0y1jasaHJyM7UroDMHtIz
"""

def saludar_alumnos():
  print("Hola alumnos bienvenidos a clases")

saludar_alumnos() #Sin argumentos y sin retornos

def obtener_año_actual():
  año = 2026
  return año
funcion_año = obtener_año_actual() #Sin argumentos y con retorno
print(funcion_año)

def mostrar_estado(nombre, nota):
  if nota >= 4.0:
    estado = "Aprobo"
  else:
    estado = "Reprobo"
  print(nombre)
  print(nota)
  print(estado)
mostrar_estado(input("Ingresa el nombre: "), float(input("Ingresa la nota: "))) #Con argumentos y sin retornos

def calcular_promedio(notas):
  total = sum(notas)
  prom = total / len(notas)
  return round(prom, 1)

notas_ana = [6.5, 5.8, 7.0]
prom_ana = calcular_promedio(notas_ana)
print(f"El promedio de Ana es: {prom_ana}")

notas_hector = [6.0, 5.1, 7.0]
prom_hector = calcular_promedio(notas_hector)
print(f"El promedio de Hector es: {prom_hector}")  #CON ARGUMENTO Y CON RETORNO

def mostrar_menu(): #EJERCICIO 1
  print("1.- °C -> °F")
  print("2.- °F -> °C")
  print("3.- Salir")

mostrar_menu()

def pedir_temperatura(): #EJERCICIO 2
  temperatura = float(input("Ingresa la temperatura en grados °C: "))
  return temperatura
funcion_temperatura = pedir_temperatura()
print("La temperatura en °C es: ",funcion_temperatura)

c = float(input("Ingresa la temperatura en °C: "))
def celsius_a_f(c):
  return(c *9/5) +32
celsius_a_f(c)

f = float(input("Ingresa la temperatura en °F: "))
def fahrenheit_a_c(f):
  return(f -32) *5/9
fahrenheit_a_c(f)

def mostrar_resultado(orig, conv, ud): #EJERCICIO 3
  print(orig)
  print(conv)
  print(ud)
mostrar_resultado(26, 77, "CF")